In [3]:
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.9.2'

# Constants

In [5]:
tensor = tf.constant([[23, 4], [32, 51]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [6]:
tensor.shape

TensorShape([2, 2])

In [7]:
tensor.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [8]:
np_array = np.array([[23, 4], [32, 51]])

In [9]:
tensor_fromnp = tf.constant(np_array)
tensor_fromnp

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

# Variables

In [10]:
tf_var = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [11]:
tf_var[0, 2].assign(100)
tf_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

# Operations

In [12]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [14]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [15]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [17]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [18]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [19]:
np.dot(tensor, tensor)

array([[ 7, 10],
       [15, 22]], dtype=int32)

# Strings

In [20]:
tf_str = tf.constant("Tensorflow")
tf_str

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow'>

In [21]:
tf.strings.length(tf_str)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [22]:
tf.strings.unicode_decode(tf_str, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

In [23]:
tf_str_array = tf.constant(["Tensorflow", "Deep Learning", "AI"])
tf_str_array

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'Tensorflow', b'Deep Learning', b'AI'], dtype=object)>

In [24]:
for string in tf_str_array:
  print(string)

tf.Tensor(b'Tensorflow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
