In [3]:
import datetime
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

In [7]:
tf.__version__

'2.9.2'

# Preprocessing

## Load Data

In [8]:
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step


In [10]:
X_train[0][:2]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]], dtype=uint8)

In [11]:
y_train[0]

9

## Normalize Images

In [12]:
X_train = X_train / 255.0

In [13]:
X_test = X_test / 255.0

In [14]:
X_train[0][:2]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Reshaping

In [15]:
X_train.shape

(60000, 28, 28)

In [16]:
X_train = X_train.reshape(-1, 28*28)

In [17]:
X_train.shape

(60000, 784)

In [18]:
X_train[0][:2]

array([0., 0.])

In [19]:
X_test = X_test.reshape(-1, 28*28)

In [20]:
X_test.shape

(10000, 784)

# Build model

## Defining model

It is sequential because it is a layer sequence

In [21]:
model = tf.keras.models.Sequential()

In [22]:
model

Adding layers

In [24]:
model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)))

In [25]:
model.add(tf.keras.layers.Dropout(0.2))

Como son más de 2 clases se usa softmax, sino sería sigmoide

In [26]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

## Compiling model

Se usa sparse porque la salida no está en One Hot Encoding

In [30]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [31]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


## Train model

In [32]:
model.fit(X_train, y_train, epochs= 5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.5342 - sparse_categorical_accuracy: 0.8090
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3969 - sparse_categorical_accuracy: 0.8549
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3633 - sparse_categorical_accuracy: 0.8659
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3424 - sparse_categorical_accuracy: 0.8740
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3286 - sparse_categorical_accuracy: 0.8780


## Evaluation

In [33]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.3486 - sparse_categorical_accuracy: 0.8767


In [34]:
print("Test accuracy: {}".format(test_accuracy))

Test accuracy: 0.8766999840736389


In [35]:
test_loss

0.3486472964286804

# Improving

In [36]:
model = tf.keras.models.Sequential()

In [37]:
model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784,)))

In [38]:
model.add(tf.keras.layers.Dropout(0.2))

In [39]:
model.add(tf.keras.layers.Dense(units=128, activation='relu'))

In [40]:
model.add(tf.keras.layers.Dropout(0.2))

In [41]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

In [42]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [43]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 128)               100480    
                                                                 
 dropout_1 (Dropout)         (None, 128)               0         
                                                                 
 dense_3 (Dense)             (None, 128)               16512     
                                                                 
 dropout_2 (Dropout)         (None, 128)               0         
                                                                 
 dense_4 (Dense)             (None, 10)                1290      
                                                                 
Total params: 118,282
Trainable params: 118,282
Non-trainable params: 0
_________________________________________________________________


In [44]:
model.fit(X_train, y_train, epochs= 10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.5497 - sparse_categorical_accuracy: 0.8011
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4149 - sparse_categorical_accuracy: 0.8478
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3836 - sparse_categorical_accuracy: 0.8590
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3608 - sparse_categorical_accuracy: 0.8673
Epoch 5/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3464 - sparse_categorical_accuracy: 0.8724
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3357 - sparse_categorical_accuracy: 0.8765
Epoch 7/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3219 - sparse_categorical_accuracy: 0.8802
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3160 - sparse_categorical_accuracy: 0.8838
Epoch 9/10
1875/1875 [==========

In [45]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.3313 - sparse_categorical_accuracy: 0.8811


In [46]:
print("Test accuracy: {}".format(test_accuracy))

Test accuracy: 0.8810999989509583


# Save model

In [47]:
model_json = model.to_json()
with open("fashion_model.json", "w") as json_file:
  json_file.write(model_json)

# Save weights

In [48]:
model.save_weights("fashion_model.h5")